ALTER TABLE EQUIPOS ADD CONSTRAINT RST_PUNTOS CHECK (PUNTOS >= 0);
ALTER TABLE EQUIPOS ADD CONSTRAINT RST_PJ CHECK (PJ >= 0);
ALTER TABLE EQUIPOS ADD CONSTRAINT RST_PG CHECK (PG >= 0);
ALTER TABLE EQUIPOS ADD CONSTRAINT RST_PP CHECK (PP >= 0);
ALTER TABLE EQUIPOS ADD CONSTRAINT RST_PE CHECK (PE >= 0);

ALTER TABLE PARTIDOS ADD CONSTRAINT RST_GOLES CHECK (GOLESLOCAL >= 0 AND GOLESVISITANTE >=0);

ALTER TABLE PARTIDOS
ADD CONSTRAINT CHCK_PARTIDOS CHECK ( estado in ('Jugado', 'Jugando' , 'Sin jugar'));