-- INSERCCIÓN DE DATOS --

INSERT INTO jugadores (nombre,apellido1,apellido2) VALUES ('Juan', 'Perez', 'Molina');
INSERT INTO jugadores (nombre,apellido1,apellido2) VALUES ('Jose', 'Molina', 'Muñoz');
INSERT INTO jugadores (nombre,apellido1,apellido2) VALUES ('Antonio', 'Fernandez', 'Murillo');

INSERT INTO EQUIPOS (NOMBRE,PJ,PG,PP,PE,PUNTOS,GOLES_FAVOR,GOLES_CONTRA,DIFERENCIA_GOLES) VALUES ('1DAW',0,0,0,0,0,0,0,0);
INSERT INTO EQUIPOS (NOMBRE,PJ,PG,PP,PE,PUNTOS,GOLES_FAVOR,GOLES_CONTRA,DIFERENCIA_GOLES) VALUES ('2DAW',0,0,0,0,0,0,0,0);
INSERT INTO EQUIPOS (NOMBRE,PJ,PG,PP,PE,PUNTOS,GOLES_FAVOR,GOLES_CONTRA,DIFERENCIA_GOLES) VALUES ('1ASIR',0,0,0,0,0,0,0,0);
INSERT INTO EQUIPOS (NOMBRE,PJ,PG,PP,PE,PUNTOS,GOLES_FAVOR,GOLES_CONTRA,DIFERENCIA_GOLES) VALUES ('2ASIR',0,0,0,0,0,0,0,0);