-- MySQL Script generated by MySQL Workbench
-- 02/03/17 11:13:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gestion_Academica_BSG` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Gestion_Academica_BSG` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ciclos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Academica_BSG`.`Ciclos` (
  `Ciclos` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Ciclos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Academica_BSG`.`Alumnos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  /*UNIQUE INDEX `email_UNIQUE` (`email` ASC),*/
  INDEX `idAlumnos` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Academica_BSG`.`Grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `aula` VARCHAR(10) NULL,
  `ciclo` VARCHAR(5) NOT NULL,
  `idAlumno` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Grupos_Ciclos_idx` (`ciclo` ASC),
  INDEX `idDelegado_idx` (`idAlumno` ASC),
  CONSTRAINT `fk_Grupos_Ciclos`
    FOREIGN KEY (`ciclo`)
    REFERENCES `Gestion_Academica_BSG`.`Ciclos` (`Ciclos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDelegado`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `Gestion_Academica_BSG`.`Alumnos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Academica_BSG`.`Asignaturas` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nhoras` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Academica_BSG`.`Notas` (
  `Alumnos_id` INT NOT NULL,
  `Asignaturas_id` INT NOT NULL,
  `id` INT NOT NULL,
  `1Ev` INT NULL,
  `2Ev` INT NULL,
  `3Ev` INT NULL,
  `Final` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Alumnos_has_Asignaturas_Asignaturas1_idx` (`Asignaturas_id` ASC),
  INDEX `fk_Alumnos_has_Asignaturas_Alumnos1_idx` (`Alumnos_id` ASC),
  CONSTRAINT `fk_Alumnos_has_Asignaturas_Alumnos1`
    FOREIGN KEY (`Alumnos_id`)
    REFERENCES `Gestion_Academica_BSG`.`Alumnos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumnos_has_Asignaturas_Asignaturas1`
    FOREIGN KEY (`Asignaturas_id`)
    REFERENCES `Gestion_Academica_BSG`.`Asignaturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delegado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Academica_BSG`.`Delegado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idGrupos` INT NOT NULL,
  `idAlumnos` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idGrupos_idx` (`idGrupos` ASC),
  INDEX `idAlumnos_idx` (`idAlumnos` ASC),
  CONSTRAINT `idGrupos`
    FOREIGN KEY (`idGrupos`)
    REFERENCES `Gestion_Academica_BSGCA`.`Grupos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAlumnos`
    FOREIGN KEY (`idAlumnos`)
    REFERENCES `Gestion_Academica_BSG`.`Alumnos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Academica_BSG`.`Profesores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imparte`
-- -----------------------------------------------------
CREATE TABLE `imparte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idGrupos` INT NOT NULL,
  `idProfesores` INT NOT NULL,
  `idAsignaturas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idGrupos_idx` (`idGrupos` ASC),
  INDEX `idProfesores_idx` (`idProfesores` ASC),
  INDEX `idAsignaturas_idx` (`idAsignaturas` ASC),
	FOREIGN KEY (`idGrupos`) REFERENCES `Gestion_Academica_BSG`.`Grupos` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (`idProfesores`) REFERENCES `Gestion_Academica_BSG`.`Profesores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (`idAsignaturas`) REFERENCES `Gestion_Academica_BSG`.`Asignaturas` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)

