-- MOSTRAR EK NUMERO DE MANAGER, EL SALARIO DEL JEFE PEOR PAGADO PARA AQUELLOS EMPLEADOS QUE TENGAN MANAGER Y EXCLUYENDO AQUELLOS CUYO MINIMO
-- SALARIO MENOR DE 1000 DOLARES EN ORDEN DESCENDIENTE DE SALARIO MININO

SELECT MGR, MIN(SAL)
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY MGR HAVING MIN(SAL) > 1000
ORDER BY MIN(SAL) DESC;

-- 
