ALTER TABLE EQUIPOS
ADD CONSTRAINT PTOS_CK  CHECK (PTOS > 0);

ALTER TABLE EQUIPOS
ADD CONSTRAINT PP_CK CHECK (PP > 0);

ALTER TABLE EQUIPOS
ADD CONSTRAINT PE_CK  CHECK (PE > 0);

ALTER TABLE EQUIPOS
ADD CONSTRAINT PG_CK  CHECK (PG > 0);

ALTER TABLE EQUIPOS
ADD CONSTRAINT PJ_CK  CHECK (PJ > 0);
