CREATE OR REPLACE FUNCTION SACAR_NOMBRE_EQUIPO (ID_EQUIPO IN NUMBER )

RETURN VARCHAR2 IS
NOMBRE_EQUIPO EQUIPOS.NOMBRE%TYPE;

BEGIN

    SELECT EQUIPOS.NOMBRE
    INTO NOMBRE_EQUIPO
    FROM EQUIPOS
    WHERE EQUIPOS.ID = ID_EQUIPO;

  RETURN NOMBRE_EQUIPO;
END SACAR_NOMBRE_EQUIPO;
