CREATE TABLE ALUMNOS (

  ID NUMBER,
  NOMBRE VARCHAR2(255),
  APELLIDO1 VARCHAR2(255),
  APELLIDO2 VARCHAR2(255),

  PRIMARY KEY(ID)

);

CREATE TABLE ASIGNATURAS(

  ID NUMBER,
  NOMBRE VARCHAR2(255),
  NHORAS NUMBER,

  PRIMARY KEY (ID)
);

CREATE TABLE NOTAS (

  ID NUMBER,
  ID_ALUMNO NUMBER,
  ID_ASIGNATURA NUMBER,
  PRIMERA_EV NUMBER,
  SEGUNDA_EV NUMBER,
  TERCERA_EV NUMBER,
  ccMEDIA NUMBER,

  PRIMARY KEY (ID),
  FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS(ID),
  FOREIGN KEY (ID_ASIGNATURA) REFERENCES ALUMNOS(ID),
  UNIQUE(ID_ALUMNO,ID_ASIGNATURA)
);
