CREATE OR REPLACE FUNCTION calculo_nota (NOTA IN NUMBER )

RETURN VARCHAR2 IS

MENSAJE VARCHAR2(255);

BEGIN

    IF NOTA < 5 THEN
      MENSAJE := 'INSUFICIENTE';
    ELSIF NOTA >= 5 OR NOTA < 6 THEN
      MENSAJE := 'SUFICIENTE';
    ELSIF NOTA >= 6 OR NOTA < 7 THEN
      MENSAJE := 'BIEN';
    ELSIF NOTA >= 7 OR NOTA < 9 THEN
      MENSAJE := 'BIEN';
    ELSIF NOTA >= 9 OR NOTA < 10 THEN
      MENSAJE := 'SOBRESALIENTE';
    END IF;


  RETURN MENSAJE;
END calculo_nota;
