create or replace PROCEDURE crea_informe (P_ASIGNATURA IN VARCHAR2) AS


    CURSOR C_ALUMNOS IS
    SELECT ccMEDIA FROM ALUMNOS, NOTAS, ASIGNATURAS
    WHERE NOTAS.ID_ALUMNO = ALUMNOS.ID AND NOTAS.ID_ASIGNATURA = ASIGNATURAS.ID AND ASIGNATURAS.NOMBRE = P_ASIGNATURA ;


    TOTAL_ALUMNOS NUMBER;




    NUMERO_INSUFICIENTES NUMBER;
    NUMERO_SUFICIENTES NUMBER;
    NUMERO_BIEN NUMBER;
    NUMERO_NOTABLES NUMBER;
    NUMERO_SOBRESALIENTES NUMBER;




BEGIN


      NUMERO_INSUFICIENTES := 0;
      NUMERO_SUFICIENTES := 0;
      NUMERO_BIEN := 0;
      NUMERO_NOTABLES := 0;
      NUMERO_SOBRESALIENTES :=0;

  SELECT count(*)
     INTO TOTAL_ALUMNOS
     FROM ALUMNOS;

    FOR ALUMNO IN C_ALUMNOS LOOP

        IF calculo_nota(ALUMNO.ccMEDIA) = 'INSUFICIENTE' THEN

          NUMERO_INSUFICIENTES := NUMERO_INSUFICIENTES + 1;

        END IF;

        IF calculo_nota(ALUMNO.ccMEDIA) = 'SUFICIENTE' THEN

          NUMERO_SUFICIENTES := NUMERO_SUFICIENTES + 1;

        END IF;

        IF calculo_nota(ALUMNO.ccMEDIA) = 'BIEN' THEN

          NUMERO_BIEN := NUMERO_BIEN + 1;

        END IF;

        IF calculo_nota(ALUMNO.ccMEDIA) = 'NOTABLE' THEN

          NUMERO_NOTABLES := NUMERO_NOTABLES + 1;

        END IF;

        IF calculo_nota(ALUMNO.ccMEDIA) = 'SOBRESALIENTE' THEN

          NUMERO_SOBRESALIENTES := NUMERO_SOBRESALIENTES + 1;

        END IF;

      END LOOP;

      IF NUMERO_INSUFICIENTES > 0 THEN
          DBMS_OUTPUT.PUT_LINE('INSUFICIENTES ' || TOTAL_ALUMNOS/NUMERO_INSUFICIENTES || '%');
        ELSIF NUMERO_INSUFICIENTES = 0 THEN
          DBMS_OUTPUT.PUT_LINE('INSUFICIENTES ' || 0 || '%');
      END IF;

      IF NUMERO_SUFICIENTES > 0 THEN
          DBMS_OUTPUT.PUT_LINE('SUFICIENTES ' || TOTAL_ALUMNOS/NUMERO_SUFICIENTES || '%');
        ELSIF NUMERO_SUFICIENTES = 0 THEN
          DBMS_OUTPUT.PUT_LINE('SUFICIENTES ' || 0 || '%');
      END IF;

      IF NUMERO_BIEN > 0 THEN
          DBMS_OUTPUT.PUT_LINE('BIEN ' || TOTAL_ALUMNOS/NUMERO_BIEN || '%');
        ELSIF NUMERO_BIEN = 0 THEN
          DBMS_OUTPUT.PUT_LINE('BIEN ' || 0 || '%');
      END IF;

      IF NUMERO_NOTABLES > 0 THEN
          DBMS_OUTPUT.PUT_LINE('NOTABLES ' || TOTAL_ALUMNOS/NUMERO_NOTABLES || '%');
        ELSIF NUMERO_NOTABLES = 0 THEN
          DBMS_OUTPUT.PUT_LINE('NOTABLES ' || 0 || '%');
      END IF;

      IF NUMERO_SOBRESALIENTES > 0 THEN
          DBMS_OUTPUT.PUT_LINE('SOBRESALIENTE ' || TOTAL_ALUMNOS/NUMERO_SOBRESALIENTES || '%');
        ELSIF NUMERO_SOBRESALIENTES = 0 THEN
          DBMS_OUTPUT.PUT_LINE('SOBRESALIENTE ' || 0 || '%');
      END IF;


END crea_informe;
