CREATE TABLE COCHES (

  ID NUMBER,
  MATRICULA VARCHAR2(20),
  COLOR VARCHAR2(100),

  ID_MODELO NUMBER,

  PRIMARY KEY (ID)

);

CREATE TABLE MODELOS (

  ID  NUMBER,
  MODELO VARCHAR2(255),

  ID_MARCA NUMBER,

  PRIMARY KEY (ID)

);

CREATE TABLE MARCAS (

  ID NUMBER,
  MARCA VARCHAR2(255),

  PRIMARY KEY (ID),
  UNIQUE(MARCA)

);

CREATE TABLE CLIENTES (

  ID NUMBER,
  NIF VARCHAR2(30),
  NOMBRE VARCHAR2(255),
  DIRECCION VARCHAR2(255),
  CIUDAD VARCHAR2(255),
  TELEFONO VARCHAR2(50),

  PRIMARY KEY (ID)

);

CREATE TABLE REVISIONES (

  ID NUMBER,
  C_FILTRO BOOLEAN,
  C_ACEITE BOOLEAN,
  C_FRENOS BOOLEAN,

  ID_COCHE NUMBER,

  PRIMARY KEY (ID)

);

CREATE TABLE VENTAS (

  ID NUMBER,

  ID_COCHE NUMBER,
  ID_CLIENTE NUMBER,

  PRIMARY KEY (ID),
  UNIQUE(ID_COCHE,ID_CLIENTE)

);

-- FOREIGN KEYS --

-- COCHES --
ALTER TABLE COCHES
ADD CONSTRAINT FK_MODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELOS(ID);

-- MODELOS --
ALTER TABLE MODELOS
ADD CONSTRAINT FK_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCAS(ID);

-- REVISIONES --
ALTER TABLE REVISIONES
ADD CONSTRAINT FK_COCHE FOREIGN KEY (ID_COCHE) REFERENCES COCHES(ID);

-- VENTAS --
ALTER TABLE VENTAS
ADD CONSTRAINT FK_COCHE_VENTA FOREIGN KEY (ID_COCHE) REFERENCES COCHES(ID);

ALTER TABLE VENTAS
ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID);
