CREATE TABLE AUTORES(

    ID NUMBER,
    NOMBRE VARCHAR2(255),
    APELLIDOS VARCHAR2(255),

    PRIMARY KEY (ID)

);

CREATE TABLE LIBROS(

    ID NUMBER,
    TITULO VARCHAR2(255),
    ID_GENERO NUMBER,
    ID_EDITORIAL NUMBER,

    PRIMARY KEY(ID)
);

CREATE TABLE AUTORES_LIBROS (

    ID NUMBER,
    ID_AUTOR NUMBER,
    ID_LIBRO NUMBER,

    PRIMARY KEY (ID),
    UNIQUE(ID_AUTOR, ID_LIBRO)

);

CREATE TABLE EJEMPLARES (

    ID NUMBER,
    ISBN VARCHAR2(10),
    ID_LIBRO NUMBER,

    PRIMARY KEY (ID)

);

CREATE TABLE GENEROS (

    ID NUMBER,
    GENERO VARCHAR2(255),

    PRIMARY KEY(ID),
    UNIQUE(GENERO)

);

CREATE TABLE EDITORIALES (

    ID NUMBER,
    NOMBRE VARCHAR2(255),

    PRIMARY KEY(ID),
    UNIQUE(NOMBRE)

);


-- ALTER CON FOREIGN KEYS --

-- Libros --
ALTER TABLE LIBROS
ADD CONSTRAINT FK_GENERO FOREIGN KEY (ID_GENERO) REFERENCES GENEROS(ID);

ALTER TABLE LIBROS
ADD ID_EDITORIAL NUMBER;

ALTER TABLE LIBROS
ADD CONSTRAINT FK_EDITORIAL FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIALES(ID);

-- Autores y libros --
ALTER TABLE AUTORES_LIBROS
ADD CONSTRAINT FK_AUTORES FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES(ID);

ALTER TABLE AUTORES_LIBROS
ADD CONSTRAINT FK_LIBROS FOREIGN KEY (ID_LIBRO) REFERENCES LIBROS(ID);

-- Ejemplares --
ALTER TABLE EJEMPLARES
ADD CONSTRAINT FK_EJEMPLAR_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES LIBROS(ID);
