-- DATOS AUTORES --
INSERT INTO AUTORES (NOMBRE, APELLIDOS) VALUES ('AUTOR1', 'APELLIDO1 APELLIDO2');
INSERT INTO AUTORES (NOMBRE, APELLIDOS) VALUES ('AUTOR2', 'APELLIDO1 APELLIDO2');
INSERT INTO AUTORES (NOMBRE, APELLIDOS) VALUES ('AUTOR3', 'APELLIDO1 APELLIDO2');
INSERT INTO AUTORES (NOMBRE, APELLIDOS) VALUES ('AUTOR4', 'APELLIDO1 APELLIDO2');

-- DATOS GENEROS --
INSERT INTO GENEROS (GENERO) VALUES ('DRAMA');
INSERT INTO GENEROS (GENERO) VALUES ('COMEDIA');
INSERT INTO GENEROS (GENERO) VALUES ('POESIA');

-- DATOS EDITORIALES --
INSERT INTO EDITORIALES (NOMBRE) VALUES ('PLANETA');
INSERT INTO EDITORIALES (NOMBRE) VALUES ('ATALALLA');
INSERT INTO EDITORIALES (NOMBRE) VALUES ('EDITEX');

-- DATOS LIBROS --
INSERT INTO LIBROS (TITULO,ID_GENERO, ID_EDITORIAL) VALUES ('LIBRO1', 1, 1);
INSERT INTO LIBROS (TITULO,ID_GENERO, ID_EDITORIAL) VALUES ('LIBRO2', 2, 2);
INSERT INTO LIBROS (TITULO,ID_GENERO, ID_EDITORIAL) VALUES ('LIBRO3', 2, 3);
INSERT INTO LIBROS (TITULO,ID_GENERO, ID_EDITORIAL) VALUES ('LIBRO4', 1, 2);
INSERT INTO LIBROS (TITULO,ID_GENERO, ID_EDITORIAL) VALUES ('LIBRO5', 3, 1);
