CREATE SEQUENCE ID_AUTO_AUTORES START WITH 1;
CREATE SEQUENCE ID_AUTO_LIBROS START WITH 1;
CREATE SEQUENCE ID_AUTO_AUTORES_LIBROS START WITH 1;
CREATE SEQUENCE ID_AUTO_EJEMPLARES START WITH 1;
CREATE SEQUENCE ID_AUTO_GENEROS START WITH 1;
CREATE SEQUENCE ID_AUTO_EDITORIALES START WITH 1;
