select SACAR_NOMBRE_EQUIPO(IDEQUIPOLOCAL), SACAR_NOMBRE_EQUIPO(IDEQUIPOVISITANTE) from partidos;

EXEC NOMBRE_PROCEDIMIENTO;


SELECT E1.NOMBRE, E2.NOMBRE
FROM EQUIPOS E1, EQUIPOS E2
WHERE E1.ID <> E2.ID;

UPDATE PARTIDOS SET GOLESLOCAL = 0, GOLESVISITANTE = 0 WHERE ID = 1;
UPDATE PARTIDOS SET GOLESLOCAL = 3, GOLESVISITANTE = 0 WHERE ID = 2;
UPDATE PARTIDOS SET GOLESLOCAL = 0, GOLESVISITANTE = 3 WHERE ID = 3;