CREATE OR REPLACE FORCE VIEW "CLASIFICACION" 
(NOMBRE,PJ,PG,PE,PP,PUNTOS,GOLES_FAVOR,GOLES_CONTRA,DIFERENCIA_GOLES)
AS SELECT NOMBRE,PJ,PG,PE,PP,PUNTOS,GOLES_FAVOR,GOLES_CONTRA,DIFERENCIA_GOLES
FROM EQUIPOS ORDER BY PUNTOS DESC, DIFERENCIA_GOLES DESC, GOLES_FAVOR DESC;