
-- CHECKS PARA EQUIPOS
ALTER TABLE EQUIPOS
ADD CONSTRAINT PTOS_CK  CHECK (PTOS >= 0);

ALTER TABLE EQUIPOS
ADD CONSTRAINT PP_CK CHECK (PP >= 0);

ALTER TABLE EQUIPOS
ADD CONSTRAINT PE_CK  CHECK (PE >= 0);

ALTER TABLE EQUIPOS
ADD CONSTRAINT PG_CK  CHECK (PG >= 0);

ALTER TABLE EQUIPOS
ADD CONSTRAINT PJ_CK  CHECK (PJ >= 0);


-- CHECKS PARA PARTIDOS
ALTER TABLE PARTIDOS
ADD CONSTRAINT GV_CK  CHECK (GOLESVISITANTE >= 0);

ALTER TABLE PARTIDOS
ADD CONSTRAINT GL_CK CHECK (GOLESLOCAL >= 0);


-- Actualizaciones y mejoras --

ALTER TABLE PARTIDOS
ADD CONSTRAINT PARTIDOS_CK CHECK ( ESTADO in ('Jugado', 'Jugando' , 'Sin jugar'));
