CREATE OR REPLACE FUNCTION CALCULARLETRADNI(DNI IN NUMBER)
RETURN CHAR
IS
letra CHAR;


BEGIN

    letra := SUBSTR('RWAGMYFPDXBNJZSQVHLCKE', MOD(DNI,23)-1 , MOD(DNI,23));

  RETURN letra;
END CALCULARLETRADNI;
