create or replace FUNCTION ANNOS_TRABAJADOS_EMPRESAS (FECHA_CONTRATACION IN DATE)
RETURN NUMBER IS

ANNOS_TRABAJADOS NUMBER;
ANNO_CONTRATACION NUMBER;
ANNO_ACTUAL NUMBER;



BEGIN

    ANNO_CONTRATACION := EXTRACT(YEAR FROM FECHA_CONTRATACION);
    ANNO_ACTUAL := EXTRACT(YEAR FROM SYSDATE);
    ANNOS_TRABAJADOS := ANNO_ACTUAL - ANNO_CONTRATACION;

  RETURN ANNOS_TRABAJADOS;
END ANNOS_TRABAJADOS_EMPRESAS;
